---
name: CI (master)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: Adzz/jest_test_action@v1.0.0
        env:
          CLOUDMERSIVE_API_KEY: ${{ secrets.CLOUDMERSIVE_API_KEY }}
          DEEPAI_API_KEY: ${{ secrets.DEEPAI_API_KEY }}
          PICPURIFY_API_KEY: ${{ secrets.PICPURIFY_API_KEY }}
          SIGHTENGINE_API_KEY: ${{ secrets.SIGHTENGINE_API_USER }},${{ secrets.SIGHTENGINE_API_SECRET }}
        with:
          package-manager: npm
          command: test
