---
name: CI

on: push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Define API Keys
        run: |
          touch .env
          echo "CLOUDMERSIVE_API_KEY=${{ secrets.CLOUDMERSIVE_API_KEY }}" >> .env
          echo "DEEPAI_API_KEY=${{ secrets.DEEPAI_API_KEY }}" >> .env
          echo "PICPURIFY_API_KEY=${{ secrets.PICPURIFY_API_KEY }}" >> .env
          echo "SIGHTENGINE_API_KEY=${{ secrets.SIGHTENGINE_API_USER }},${{ secrets.SIGHTENGINE_API_SECRET }}" >> .env
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: test
